/******************************************************************************
 *
 * Module: Multiplexed Seven Segements
 *
 * File Name: multiplexed7seg.c
 *
 * Description: Source file for the Two Common Cathod Multiplexed Seven Segement driver
 * with no decoder IC
 *
 * Author: Adham Nour
 *
 *******************************************************************************/
#include "multiplexed7seg.h"
#include "util/delay.h"
/*
 * Description:
 * takes a digit and display it on one of the seven segs
 */
static void Eta32mini_SevenSegment_Display(unsigned char value) {
	switch (value) {
	case 0:
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN, LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN + 1,
		LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN + 2,
		LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN + 3,
		LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN + 4,
		LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN + 5,
		LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN + 6,
		LOGIC_LOW);
		break;
	case 1:
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN, LOGIC_LOW);
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN + 1,
		LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN + 2,
		LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN + 3,
		LOGIC_LOW);
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN + 4,
		LOGIC_LOW);
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN + 5,
		LOGIC_LOW);
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN + 6,
		LOGIC_LOW);

		break;
	case 2:
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN, LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN + 1,
		LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN + 2,
		LOGIC_LOW);
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN + 3,
		LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN + 4,
		LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN + 5,
		LOGIC_LOW);
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN + 6,
		LOGIC_HIGH);

		break;
	case 3:
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN, LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN + 1,
		LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN + 2,
		LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN + 3,
		LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN + 4,
		LOGIC_LOW);
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN + 5,
		LOGIC_LOW);
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN + 6,
		LOGIC_HIGH);

		break;
	case 4:
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN, LOGIC_LOW);
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN + 1,
		LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN + 2,
		LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN + 3,
		LOGIC_LOW);
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN + 4,
		LOGIC_LOW);
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN + 5,
		LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN + 6,
		LOGIC_HIGH);
		break;
	case 5:
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN, LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN + 1,
		LOGIC_LOW);
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN + 2,
		LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN + 3,
		LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN + 4,
		LOGIC_LOW);
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN + 5,
		LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN + 6,
		LOGIC_HIGH);

		break;
	case 6:
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN, LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN + 1,
		LOGIC_LOW);
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN + 2,
		LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN + 3,
		LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN + 4,
		LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN + 5,
		LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN + 6,
		LOGIC_HIGH);
		break;
	case 7:
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN, LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN + 1,
		LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN + 2,
		LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN + 3,
		LOGIC_LOW);
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN + 4,
		LOGIC_LOW);
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN + 5,
		LOGIC_LOW);
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN + 6,
		LOGIC_LOW);

		break;
	case 8:
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN, LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN + 1,
		LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN + 2,
		LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN + 3,
		LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN + 4,
		LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN + 5,
		LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN + 6,
		LOGIC_HIGH);
		break;
	case 9:
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN, LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN + 1,
		LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN + 2,
		LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN + 3,
		LOGIC_LOW);
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN + 4,
		LOGIC_LOW);
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN + 5,
		LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEG_OUTPUT_PORT, SEVEN_SEG_START_PIN + 6,
		LOGIC_HIGH);
		break;
	}
}

/*
 * Description:
 * The functions displays the output on the seven segement
 * the maximum number to display is 99
 */

void MULTIPLEXED7SEG_displayNumber(uint8 num) {
	GPIO_togglePin(SEVEN_SEG_CONTROL_PORT, SEVEN_SEG_CONTROL_START_PIN);
	GPIO_togglePin(SEVEN_SEG_CONTROL_PORT, SEVEN_SEG_CONTROL_START_PIN + 1);
	Eta32mini_SevenSegment_Display(num / 10);

	_delay_ms(60);
	GPIO_togglePin(SEVEN_SEG_CONTROL_PORT, SEVEN_SEG_CONTROL_START_PIN);
	GPIO_togglePin(SEVEN_SEG_CONTROL_PORT, SEVEN_SEG_CONTROL_START_PIN + 1);
	Eta32mini_SevenSegment_Display(num % 10);

	_delay_ms(60);

}

/*
 * Description:
 * initilze the sevensegs
 */
void MULTIPLEXED7SEG_init() {
	/*
	 * Intializing the GPIO for the seven segements
	 */
	GPIO_setupPortDirection(SEVEN_SEG_OUTPUT_PORT, PORT_OUTPUT); 											/*declaring the seven seg port as output port */
	GPIO_setupPinDirection(SEVEN_SEG_CONTROL_PORT, SEVEN_SEG_CONTROL_START_PIN,PIN_OUTPUT);					/*declaring the first control pin as output pin*/
	GPIO_setupPinDirection(SEVEN_SEG_CONTROL_PORT,SEVEN_SEG_CONTROL_START_PIN + 1, PIN_OUTPUT);				/*declaring the second control pin as output pin*/
	GPIO_writePin(SEVEN_SEG_CONTROL_PORT, SEVEN_SEG_CONTROL_START_PIN,LOGIC_HIGH);							/*initializing the first controll pin to be LOGIC_HIGH*/
	GPIO_writePin(SEVEN_SEG_CONTROL_PORT, SEVEN_SEG_CONTROL_START_PIN + 1,LOGIC_LOW);						/*initializing the second controll pin to be LOGIC_LOW*/
}
